/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.form.admin;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 09-03-2007
 * 
 * XDoclet definition:
 * @struts.form name="AdminAddServiceForm"
 */
public class AdminUploadFileForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** serviceName property */
	private String type;
	private FormFile file;
	/*
	 * Generated Methods
	 */

	

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}



	public String getType() {
		return type;
	}



	public void setType(String type) {
		this.type = type;
	}



	public FormFile getFile() {
		return file;
	}



	public void setFile(FormFile file) {
		this.file = file;
	}

	/** 
	 * Returns the serviceName.
	 * @return String
	 */
	
}