/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.form.admin;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 09-03-2007
 * 
 * XDoclet definition:
 * @struts.form name="AdminAddServiceForm"
 */
public class AdminAddServiceForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** serviceName property */
	private String serviceName;
    private String serviceType;
    private String price;
    private String discount;
    private String dealClass;
    private String serviceDisp;
    private Short serviceCount;
    private Short serviceUser;
    private String serviceDescs;
    private String needConfirm;
    private String needCsDeal;
    private String chargeNote;
	/*
	 * Generated Methods
	 */

	public String getNeedCsDeal() {
		return needCsDeal;
	}

	public void setNeedCsDeal(String needCsDeal) {
		this.needCsDeal = needCsDeal;
	}

	public String getNeedConfirm() {
		return needConfirm;
	}

	public void setNeedConfirm(String needConfirm) {
		this.needConfirm = needConfirm;
	}

	public String getServiceDescs() {
		return serviceDescs;
	}

	public void setServiceDescs(String serviceDescs) {
		this.serviceDescs = serviceDescs;
	}

	public Short getServiceUser() {
		return serviceUser;
	}

	public void setServiceUser(Short serviceUser) {
		this.serviceUser = serviceUser;
	}

	public String getDealClass() {
		return dealClass;
	}

	public void setDealClass(String dealClass) {
		this.dealClass = dealClass;
	}

	public Short getServiceCount() {
		return serviceCount;
	}

	public void setServiceCount(Short serviceCount) {
		this.serviceCount = serviceCount;
	}

	public String getServiceDisp() {
		return serviceDisp;
	}

	public void setServiceDisp(String serviceDisp) {
		this.serviceDisp = serviceDisp;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the serviceName.
	 * @return String
	 */
	public String getServiceName() {
		return serviceName;
	}

	/** 
	 * Set the serviceName.
	 * @param serviceName The serviceName to set
	 */
	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getDiscount() {
		return discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getServiceType() {
		return serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public String getChargeNote() {
		return chargeNote;
	}

	public void setChargeNote(String chargeNote) {
		this.chargeNote = chargeNote;
	}
}