/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.form.article;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * @struts.form name="ClientLoginForm"
 */
public class NewsForm extends ActionForm {
	
	private Integer id;
	private Short iscommend;
	private String writer;
	private String source;
	
	private String likeid;
	private String tag;
	
	private String shorttitle;
	private String description;
	private String keywords;
	private String pubdate;
	private String color;
	
	/*
	private Date lastpost;
	
	private Date senddate;*/

	
	private Short litpictype;
	private FormFile locallitpic;
	private String litpicurl;
	private String litpicurl2;
	

	
	private String title;
	private String content;
	

	/*
	 * Generated Methods
	 */

	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		
		//System.out.println("form.likeid =  " + likeid);
		//System.out.println("form.litpictype = " + litpictype);
		//errors.add("loginName.value", new ActionMessage(loginName, false));
		//errors.add("password.value", new ActionMessage(password, false));
		
		/*request.setAttribute("LOGIN_NAME", loginName);
		request.setAttribute("PASSWORD", password);
		
		if ( loginName == null || loginName.length() < 1 ){
			errors.add("loginName.error", new ActionMessage("请输入用户名", false));
		}

		if ( password == null || password.length() < 1 ){
			errors.add("password.error", new ActionMessage("请输入密碼", false));
		}
		
		if ( validateFlag != null && validateFlag.equals("Y") ){
			if ( validateCode == null || validateCode.length() < 1 ){
				errors.add("validateCode", new ActionMessage("请输入验证码", false));
			}
			else {
				HttpSession session = request.getSession();
				String checkCode = (String) session.getAttribute("VALIDATE_CODE");
				session.removeAttribute("VALIDATE_CODE");
				
				if (!request.getParameter("validateCode").equals(checkCode)) {
					errors.add("validateCode.error", new ActionMessage("验证碼错误，請重新登錄。", false));
					//request.setAttribute("ERROR_INFO", "验证碼错误，請重新登錄。");
				}
			}
		}*/
		
		return errors;
		//return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Short getLitpictype() {
		return litpictype;
	}

	public void setLitpictype(Short litpictype) {
		this.litpictype = litpictype;
	}

	public FormFile getLocallitpic() {
		return locallitpic;
	}

	public void setLocallitpic(FormFile locallitpic) {
		this.locallitpic = locallitpic;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Short getIscommend() {
		return iscommend;
	}

	public void setIscommend(Short iscommend) {
		this.iscommend = iscommend;
	}

	public String getWriter() {
		return writer;
	}

	public void setWriter(String writer) {
		this.writer = writer;
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLikeid() {
		return likeid;
	}

	public void setLikeid(String likeid) {
		this.likeid = likeid;
	}

	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getShorttitle() {
		return shorttitle;
	}

	public void setShorttitle(String shorttitle) {
		this.shorttitle = shorttitle;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getPubdate() {
		return pubdate;
	}

	public void setPubdate(String pubdate) {
		this.pubdate = pubdate;
	}

	public String getLitpicurl() {
		return litpicurl;
	}

	public void setLitpicurl(String litpicurl) {
		this.litpicurl = litpicurl;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getLitpicurl2() {
		return litpicurl2;
	}

	public void setLitpicurl2(String litpicurl2) {
		this.litpicurl2 = litpicurl2;
	}

	

	

}