/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.article;

import java.util.Date;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.exception.ForbesException;
import com.forbes.hibernate.bean.Article;
import com.forbes.hibernate.bean.Comment;
import com.forbes.hibernate.bean.CommentType;
import com.forbes.hibernate.bean.UcMembers;
import com.forbes.hibernate.bean.User;
import com.forbes.service.article.ContentManager;
import com.forbes.service.article.ArticleListManager;
import com.forbes.service.user.UserInfoManager;
import com.forbes.service.user.UserLogin;
import com.forbes.struts.form.user.UserLoginForm;
import com.forbes.util.MD5;


/** 
 * MyEclipse Struts
 * Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * @struts.action path="/client/ClientLogin" name="clientLoginForm" attribute="ClientLoginForm" input="/client/ClientLogin.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/client/ClientLoginOk.jsp"
 * @struts.action-forward name="fail" path="/client/ClientLoginFail.jsp"
 */
public class ContentDeleteAction extends Action {
	/*#com.she.web.form.client.ClientLoginForm Dependency20*/
/*
	 * Generated Methods
	 */

	private ContentManager contentManager;
	
	//private ArticleListManager articleListManager;
	
	
	//private  UserInfoManager userInfoManager;
	
	
	
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws ForbesException {
		
		//UserLoginForm userLoginForm = (UserLoginForm) form;// TODO Auto-generated method stub
		//System.out.println("---------------------ArticleContentAddAction" );
		
		String id	 		 = request.getParameter("id");		
		//UcMembers user = (UcMembers)request.getSession().getAttribute("CLIENT");
		
		try {
			Comment ac = contentManager.getContent(Long.parseLong(id));
			contentManager.deleteContent(ac);
			request.setAttribute("RESULT_MESSAGE", "SUCCESS" );
			//request.setAttribute("RETURN_URL", "ArticleView.do?id="+id );
			return mapping.findForward("ok");
		} catch (Exception e) {
				e.printStackTrace();
				request.setAttribute("RESULT_MESSAGE", "FAIL" );
				return mapping.findForward("ok");
		}
		

	}



	public ContentManager getContentManager() {
		return contentManager;
	}

	public void setContentManager(ContentManager contentManager) {
		this.contentManager = contentManager;
	}
	
}