/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.article;

import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.hibernate.bean.Article;
import com.forbes.hibernate.bean.News;
import com.forbes.service.article.NewsManager;
import com.forbes.util.Pager;

/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class NewsSearchAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	//private VideoTypeManager videoTypeManager;
	
	private NewsManager newsManager;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward top(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		try {
			
			List list = newsManager.getTopNews(null, 0, 15);

			request.setAttribute( "NEWS_LIST", list);
			
			
			return mapping.findForward("top");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String keyword   = request.getParameter("keyword");
		String orderby   = request.getParameter("orderby");
		String pageNo    = request.getParameter("pno");
		String parameter = "keyword=" + ( (keyword==null)?" ":keyword );
		
		Map map = new TreeMap();
		map.put("keyWord", keyword);
		map.put("orderby", orderby);

		
		try {
						
			int iPageNo = 1;
			try {
				if( pageNo != null ){
					iPageNo = Integer.parseInt( pageNo );
				}
			} catch( Exception e ){ }

			List list = null;
			Pager pager = new Pager();
			pager.setCntOfPage( 5 );
			pager.setCurPage( iPageNo );
			
			list = newsManager.getNewsByPage(pager, iPageNo, keyword, orderby);

						
			request.setAttribute( "PARA", map );
			request.setAttribute( "PAGER", pager );
			request.setAttribute( "NEWS_LIST", list);

			
			
			return mapping.findForward("list");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}

	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		String  id = request.getParameter("id");

		try {
			
			News news = newsManager.getNews(Integer.parseInt(id));
			news.setClick(news.getClick() + 1);
			newsManager.updateNews(news);
			request.setAttribute( "NEWS", news);
			
			News nextNews  = newsManager.getNextNews(Integer.parseInt(id));
			News preNews   = newsManager.getPreNews(Integer.parseInt(id));
			
			request.setAttribute( "NEXT_NEWS", nextNews);
			request.setAttribute( "PRE_NEWS", preNews);
			
			return mapping.findForward("view");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public NewsManager getNewsManager() {
		return newsManager;
	}

	public void setNewsManager(NewsManager newsManager) {
		this.newsManager = newsManager;
	}
	
	public ActionForward like(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		String  id = request.getParameter("id");
		
		
		try {
			
			News news = newsManager.getNews(Integer.parseInt(id));
			List list = null;
			
			
			String likeid = news.getLikeid();
			if( likeid != null ){
				likeid = likeid.replaceAll(",", "_");
				likeid = likeid.replaceAll(" ", "_");
				list = newsManager.getLikeNews(likeid, "pubdate DESC", 0, 10);
			}
			else {
				list = newsManager.getTopNews("pubdate DESC", 0, 10);
			}
			
			
			request.setAttribute( "LIKE_NEWS_LIST", list);

			return mapping.findForward("like");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
}