/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.article;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.service.article.ArticleListManager;
import com.forbes.service.article.NewsManager;
import com.forbes.service.ucenter.UchomeManager;
import com.forbes.service.user.UserInfoManager;
import com.forbes.service.video.VideoListManager;

/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class IndexNewAction extends Action {
	/*
	 * Generated Methods
	 */
	
	private ArticleListManager articleListManager;
	
	private UserInfoManager userInfoManager;
	
	private NewsManager newsManager;
	
	private UchomeManager uchomeManager;
	
	public UchomeManager getUchomeManager() {
		return uchomeManager;
	}

	public void setUchomeManager(UchomeManager uchomeManager) {
		this.uchomeManager = uchomeManager;
	}

	public NewsManager getNewsManager() {
		return newsManager;
	}

	public void setNewsManager(NewsManager newsManager) {
		this.newsManager = newsManager;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {		
		try {
			
			request.setAttribute( "NEW_ARTICLE_LIST_TYPE_5",  articleListManager.getTopArticleByArticleType("5", "pubdate DESC", 0, 10));
			request.setAttribute( "NEW_ARTICLE_LIST_TYPE_26", articleListManager.getTopArticleByArticleType("26", "pubdate DESC", 0, 10));
			request.setAttribute( "NEW_ARTICLE_LIST_TYPE_42", articleListManager.getTopArticleByArticleType("42", "pubdate DESC", 0, 10));
			request.setAttribute( "NEW_ARTICLE_LIST_TYPE_17", articleListManager.getTopArticleByArticleType("17", "pubdate DESC", 0, 10));
			request.setAttribute( "NEW_ARTICLE_LIST_TYPE_10", articleListManager.getTopArticleByArticleType("10", "pubdate DESC", 0, 10));
			request.setAttribute( "NEW_ARTICLE_LIST_TYPE_49", articleListManager.getTopArticleByArticleType("49", "pubdate DESC", 0, 10));
			request.setAttribute( "NEW_ARTICLE_LIST_TYPE_35", articleListManager.getTopArticleByArticleType("35", "pubdate DESC", 0, 10));
			request.setAttribute( "NEW_ARTICLE_LIST_TYPE_16", articleListManager.getTopArticleByArticleType("16", "pubdate DESC", 0, 10));
			
			
			request.setAttribute( "NEWS_LIST", newsManager.getTopNews(null, 0, 15));
			request.setAttribute( "USER_LIST", userInfoManager.getNewRegister("regdate DESC", 0, 5));
			
			request.setAttribute( "TOP_ARTICLE_LIST", articleListManager.getTopArticleByArticleType(null, "click DESC", 0, 10));
			request.setAttribute( "COMMEND_ARTICLE_LIST", articleListManager.getTopArticleByArticleType(null, "iscommend DESC", 0, 10));
			
			request.setAttribute( "UC_HOME_BLOG_LIST", uchomeManager.getUchomeBlogs("viewnum", 0, 10));
						
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public ArticleListManager getArticleListManager() {
		return articleListManager;
	}
	public void setArticleListManager(ArticleListManager articleListManager) {
		this.articleListManager = articleListManager;
	}

	public UserInfoManager getUserInfoManager() {
		return userInfoManager;
	}

	public void setUserInfoManager(UserInfoManager userInfoManager) {
		this.userInfoManager = userInfoManager;
	}
	

	
}