/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.article;
import java.util.Date;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.hibernate.bean.Article;
import com.forbes.hibernate.bean.News;
import com.forbes.service.article.ArticleListManager;
import com.forbes.service.article.NewsManager;
import com.forbes.util.MD5;




/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class NewsDiggAction extends Action {
	/*
	 * Generated Methods
	 */
	//private VideoTypeManager videoTypeManager;
	
	private NewsManager newsManager;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		String  id = request.getParameter("id");
		
		System.out.print(" Digg id = "+id);
		try {
			
			News news = newsManager.getNews(Integer.parseInt(id));
			news.setDigg(news.getDigg() + 1);
			news.setDiggtime(new Date());
			newsManager.updateNews(news);
			
			//添加cookie
			/*try {
				
				Cookie c = new Cookie("FORBES_USER_DIGG", "");
				c.setMaxAge(60*60*24*365);
					response.addCookie(c);
		
			} catch(Exception e) {
				e.printStackTrace();
			}*/
			
			request.setAttribute( "RESULT_MESSAGE", news.getDigg());
			
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public NewsManager getNewsManager() {
		return newsManager;
	}
	public void setNewsManager(NewsManager newsManager) {
		this.newsManager = newsManager;
	}

	
	
	
	
}