/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.article;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.hibernate.bean.News;
import com.forbes.service.article.NewsManager;

/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class NewsViewAction extends Action {
	/*
	 * Generated Methods
	 */	
	private NewsManager newsManager;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String  id = request.getParameter("id");
		try {
			
			News news = newsManager.getNews(Integer.parseInt(id));
			if(news == null)
				return mapping.findForward("error");
			news.setClick(news.getClick() + 1);
			newsManager.updateNews(news);
			request.setAttribute( "NEWS", news);
			
			News nextNews  = newsManager.getNextNews(Integer.parseInt(id));
			News preNews   = newsManager.getPreNews(Integer.parseInt(id));
			
			request.setAttribute( "NEXT_NEWS", nextNews);
			request.setAttribute( "PRE_NEWS", preNews);
			
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("error");
		}
	}
	public NewsManager getNewsManager() {
		return newsManager;
	}
	public void setNewsManager(NewsManager newsManager) {
		this.newsManager = newsManager;
	}	
	
}