/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.article;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.service.ucenter.UcbbsManager;


/** 
 * MyEclipse Struts
 * Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * @struts.action path="/client/ClientLogin" name="clientLoginForm" attribute="ClientLoginForm" input="/client/ClientLogin.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/client/ClientLoginOk.jsp"
 * @struts.action-forward name="fail" path="/client/ClientLoginFail.jsp"
 */
public class TopCdbThreadsAction extends Action {
	/*#com.forbes.web.form.client.ClientLoginForm Dependency20*/
	/*
	 * Generated Methods
	 */
   private UcbbsManager ucbbsManager;
	/** 
	 * ¿Í»§µÇä›
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		
		List list = ucbbsManager.getCdbThreads("views", 0, 14);
		request.setAttribute("UC_BBS_THREAD_LIST", list);
		
		//System.out.println("UC_BBS_THREAD_LIST.size = " + list.size());
		return mapping.findForward("ok");
	}
	public UcbbsManager getUcbbsManager() {
		return ucbbsManager;
	}
	public void setUcbbsManager(UcbbsManager ucbbsManager) {
		this.ucbbsManager = ucbbsManager;
	}
	
	
   

	


}