/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.client;

import java.util.Date;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.hibernate.bean.UcMembers;
import com.forbes.hibernate.bean.User;
import com.forbes.service.ucenter.UCenterManager;
import com.forbes.service.user.UserInfoManager;
import com.forbes.service.user.UserLogin;
import com.forbes.service.useraction.UserActionTask;
import com.forbes.service.useraction.action.UserLoginAction;
import com.forbes.struts.form.user.UserLoginForm;
import com.forbes.thread.TaskManager;
import com.forbes.util.BaseEncode;
import com.forbes.util.MD5;



/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class ClientLoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private UserLogin userLogin;
	
	private  UserInfoManager userInfoManager;
	
	public UserInfoManager getUserInfoManager() {
		return userInfoManager;
	}

	public void setUserInfoManager(UserInfoManager userInfoManager) {
		this.userInfoManager = userInfoManager;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward index(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String loginName     = request.getParameter("loginName");
		String password      = request.getParameter("password");
		String remember      = request.getParameter("remember");

		try {
		
			int userCount = userLogin.getCount( "username", loginName.trim());
			if( userCount >=1) {
				UcMembers user = userLogin.clientVerifyPassword( loginName, password );
				
				if( user != null ){
					
					userLogin.updateLoginLog(user);
					user = userInfoManager.initUserDetail(user);
					request.getSession().setAttribute("CLIENT", user);				
					//System.out.println("---------admin login ok");
							
					//添加cookie
					try {
						if(remember !=null && remember.equals("Y")) {
							String cookieMsg =  user.getUid() + "@" + loginName + "@" + 
												MD5.convert(password) + "@" + new Date().getTime();
												
							Cookie c = new Cookie("FORBES", cookieMsg );
							c.setMaxAge(60*60*24*365);
							response.addCookie(c);
						}
					} catch(Exception e) {
						e.printStackTrace();
					}
							
							
					//产生活动日志
					UserActionTask actionTask = new UserActionTask();
					UserLoginAction action = new UserLoginAction( user );
					actionTask.setAction(action);
					//异步执行，放入任务管理器中
					TaskManager.getInstance().addTask( actionTask );
							
					//同步ucneter登录
					UCenterManager uc = new UCenterManager();
					uc.login(user.getUsername(), password);
					String syslogScript = uc.synlogin( user.getUid().toString() );
					request.setAttribute("SYN_LGIN", syslogScript );
					return mapping.findForward("index");
				
				} else{
						request.setAttribute("FAIL_MESSAGE", "密码错误，或者该用户已被注销。");
						return mapping.findForward("index");
				}
			} else {
				request.setAttribute("FAIL_MESSAGE", "本系统中无该用户。");
				return mapping.findForward("index");
			}
			

		}catch( Exception e ){
			//System.out.println(e.getMessage());
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}

	}
	
	public ActionForward select(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		//System.out.println("---------select login");
		UcMembers sessionUser = (UcMembers)request.getSession().getAttribute("CLIENT");
		//System.out.println(sessionUser == null);
		
		if (sessionUser == null) {
			Cookie[] cookies = request.getCookies();
	        boolean found_cookie = false;

	        for(int i = 0; i < cookies.length; i++) {
	            Cookie client = cookies[i];
	            if (client.getName().equals("FORBES")) {
	               
	            	//System.out.println("client.getValue() =  " + client.getValue());
	            	
	                String[] info    = client.getValue().split("@");
	                String id        = info[0];
	                String username  = info[1];
	                String password  = info[2];
	                
	                try {
	                	
	                	UcMembers user = userInfoManager.getUcMember(Integer.parseInt(id));
	                	
	                	/*System.out.println("password =  " + password);
	                	System.out.println("user.getPassword() =  " + user.getPassword());
	                	System.out.println("MD5.convert(password) =" + MD5.convert(password + user.getSalt()) );*/
	                	
	                    if(user.getUsername().equals(username) && 
	                    		user.getPassword().equals(MD5.convert(password + user.getSalt()))) {
	                    	//user.setLastLoginTime(new Date());
	    					//user.setLastLoginIp(request.getRemoteAddr());
	    					userLogin.updateLoginLog(user);
	    					request.getSession().setAttribute("CLIENT", user);				
	    					//System.out.println("---------client login ok");
	    					
	    					//同步ucneter登录
							UCenterManager uc = new UCenterManager();
							uc.login(user.getUsername(), password);
							String syslogScript = uc.synlogin( user.getUid().toString() );
						    request.setAttribute("SYN_LGIN", syslogScript );
						    
	    					found_cookie = true;
	    	                return mapping.findForward("index");
	                    }
	                    else
	                    	return mapping.findForward("index");
	                } catch (Exception e) {
	                	e.printStackTrace();
	                	return mapping.findForward("index");
	                }
	                
	            }
	        }

	        if (!found_cookie) {
	        	return mapping.findForward("index");

	        }
	        else
	        	return mapping.findForward("index");
		} 
		else
			return mapping.findForward("index");
			
			

	}
	
	public UserLogin getUserLogin() {
		return userLogin;
	}
	public void setUserLogin(UserLogin userLogin) {
		this.userLogin = userLogin;
	}
	
	
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String loginName     = request.getParameter("loginName");
		String password      = request.getParameter("password");
		String remember      = request.getParameter("remember");
	
		String history       = request.getParameter("history");
		
		if(history != null && history.length() > 0)
			request.setAttribute("RETURN_URL", BaseEncode.getFromBASE64(history));
		
		try {
		
				int userCount = userLogin.getCount( "username", loginName.trim());
				//System.out.println( "userCount = " + userCount);
				if( userCount >=1) {
					UcMembers user = userLogin.clientVerifyPassword( loginName, password );
					//System.out.println("user is null = " + (user != null) );
					if( user != null ){
						//if( user.getActive().equals("Y")) {
							//System.out.println(" active Y");
							/*user.setLastLoginTime(new Date());
							user.setLastLoginIp(request.getRemoteAddr());*/
							userLogin.updateLoginLog(user);
							user = userInfoManager.initUserDetail(user);
							request.getSession().setAttribute("CLIENT", user);				
							//System.out.println("---------admin login ok");
							
							//添加cookie
							try {
								if(remember.equals("Y")) {
									String cookieMsg =  user.getUid() + "@" + loginName + "@" + 
														MD5.convert(password) + "@" + new Date().getTime();
									Cookie c = new Cookie("FORBES", cookieMsg);
									c.setMaxAge(60*60*24*365);
									response.addCookie(c);
								}
							} catch(Exception e) {
								e.printStackTrace();
							}
							
							//産生活動日志
							//UserActionTask actionTask = new UserActionTask();
							//UserLoginAction action = new UserLoginAction( user );
							//actionTask.setAction(action);
							//异步执行，放入任務管理器中
							//TaskManager.getInstance().addTask( actionTask );

							//同步ucneter登录
							UCenterManager uc = new UCenterManager();
							uc.login(user.getUsername(), password);
							String syslogScript = uc.synlogin( user.getUid().toString() );
						    request.setAttribute("SYN_LGIN", syslogScript );

							return mapping.findForward("login");
						/*}
						else {
							//System.out.println(" active N");
							request.setAttribute("CLIENT", user);
							return mapping.findForward("verify");
						}*/
						
						
					}
					else{
						request.setAttribute("LOGIN_NAME", loginName);
						request.setAttribute("FAIL_MESSAGE", "密码错误，或者该用户已被注销。");
						return mapping.findForward("fail");
					}
				}
				else {
					request.setAttribute("LOGIN_NAME", loginName);
					request.setAttribute("FAIL_MESSAGE", "本系统中无该用户。");
					return mapping.findForward("fail");
				}
				
			

		}catch( Exception e ){
			request.setAttribute("LOGIN_NAME", loginName);
			//System.out.println(e.getMessage());
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}

	}
	
	public ActionForward relogin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String loginName     = request.getParameter("loginName");
		String password      = request.getParameter("password");
		String remember      = request.getParameter("remember");
	
		String history       = request.getParameter("history");
		
		if(history != null && history.length() > 0)
			request.setAttribute("RETURN_URL", BaseEncode.getFromBASE64(history));
		
		try {
		
				int userCount = userLogin.getCount("username", loginName.trim());
				//System.out.println( "userCount = " + userCount);
				if( userCount >=1) {
					UcMembers user = userLogin.clientVerifyPassword(loginName, password );
					//System.out.println("user is null = " + (user != null) );
					if( user != null ){
						//if( user.getActive().equals("Y")) {
							//System.out.println(" active Y");
							/*user.setLastLoginTime(new Date());
							user.setLastLoginIp(request.getRemoteAddr());*/
							userLogin.updateLoginLog(user);
							user = userInfoManager.initUserDetail(user);
							request.getSession().setAttribute("CLIENT", user);
							
							//添加cookie
							try {
								if(remember.equals("Y")) {
									String cookieMsg =  user.getUid() + "@" + loginName + "@" + 
														MD5.convert(password) + "@" + new Date().getTime();
									Cookie c = new Cookie("FORBES", cookieMsg);
									c.setMaxAge(60*60*24*365);
									response.addCookie(c);
								}
							} catch(Exception e) {
								e.printStackTrace();
							}
							
							//産生活動日志
							UserActionTask actionTask = new UserActionTask();
							UserLoginAction action = new UserLoginAction( user );
							actionTask.setAction(action);
							//异步执行，放入任務管理器中
							TaskManager.getInstance().addTask( actionTask );
							
							//同步ucneter登录
							UCenterManager uc = new UCenterManager();
							uc.login(user.getUsername(), password);
							String syslogScript = uc.synlogin( user.getUid().toString() );
						    request.setAttribute("SYN_LGIN", syslogScript );
						    
							return mapping.findForward("relogin");
						/*}
						else {
							request.setAttribute("LOGIN_NAME", loginName);
							request.setAttribute("FAIL_MESSAGE", "该用户还未验证Email。");
							return mapping.findForward("re_fail");
						}*/
						
						
					}
					else{
						request.setAttribute("LOGIN_NAME", loginName);
						request.setAttribute("FAIL_MESSAGE", "密码错误，或者该用户已被注销。");
						return mapping.findForward("re_fail");
					}
				}
				else {
					request.setAttribute("LOGIN_NAME", loginName);
					request.setAttribute("FAIL_MESSAGE", "本系统中无该用户。");
					return mapping.findForward("re_fail");
				}
				
			

		}catch( Exception e ){
			request.setAttribute("LOGIN_NAME", loginName);
			//System.out.println(e.getMessage());
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("re_fail");
		}

	}
	
	
	
	
	
	public ActionForward top(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		//System.out.println("---------top login");
		UcMembers sessionUser = (UcMembers)request.getSession().getAttribute("CLIENT");
		//System.out.println(sessionUser == null);
		
		if (sessionUser == null) {
			Cookie[] cookies = request.getCookies();
	        boolean found_cookie = false;

	        for(int i = 0; i < cookies.length; i++) {
	            Cookie client = cookies[i];
	            if (client.getName().equals("FORBES")) {
	               
	            	//System.out.println("client.getValue() =  " + client.getValue());
	            	
	                String[] info    = client.getValue().split("@");
	                String id        = info[0];
	                String username  = info[1];
	                String password  = info[2];
	                
	                try {
	                	
	                	UcMembers user = userInfoManager.getUcMember(Integer.parseInt(id));
	                	
	                	//System.out.println("password =  " + password);
	                	//System.out.println("user.getPassword() =  " + user.getPassword());
	                	//System.out.println("MD5.convert(password) =" + MD5.convert(password + user.getSalt()) );
	                	
	                    if(user.getUsername().equals(username) && 
	                    		user.getPassword().equals(MD5.convert(password + user.getSalt()))) {
	                    	//user.setLastLoginTime(new Date());
	    					//user.setLastLoginIp(request.getRemoteAddr());
	    					userLogin.updateLoginLog(user);
	    					request.getSession().setAttribute("CLIENT", user);				
	    					//System.out.println("---------client login ok");
	    					
	    					//同步ucneter登录
							UCenterManager uc = new UCenterManager();
							uc.login(user.getUsername(), password);
							String syslogScript = uc.synlogin( user.getUid().toString() );
						    request.setAttribute("SYN_LGIN", syslogScript );
						    
	    					found_cookie = true;
	    	                return mapping.findForward("top");
	                    }
	                    else
	                    	return mapping.findForward("top");
	                } catch (Exception e) {
	                	e.printStackTrace();
	                	return mapping.findForward("top");
	                }
	                
	            }
	        }

	        if (!found_cookie) {
	        	return mapping.findForward("top");

	        }
	        else
	        	return mapping.findForward("top");
		} 
		else
			return mapping.findForward("top");
			
			

	}
}