/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.client;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import java.util.TreeMap;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.hibernate.bean.UcMembers;
import com.forbes.hibernate.bean.UserWeekAttitude;
import com.forbes.service.plan.WeekAttitudeManager;


/**
 * MyEclipse Struts Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/client/ClientLogin" name="clientLoginForm"
 *                attribute="ClientLoginForm" input="/client/ClientLogin.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/client/ClientLoginOk.jsp"
 * @struts.action-forward name="fail" path="/client/ClientLoginFail.jsp"
 */
public class ClientManageUserWeekAttitudeAction extends DispatchAction {
	
	private WeekAttitudeManager weekAttitudeManager;
	
	
	public WeekAttitudeManager getWeekAttitudeManager() {
		return weekAttitudeManager;
	}

	public void setWeekAttitudeManager(WeekAttitudeManager weekAttitudeManager) {
		this.weekAttitudeManager = weekAttitudeManager;
	}
	
	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {

		UcMembers user = (UcMembers) request.getSession()
				.getAttribute("CLIENT");
		
		String date = request.getParameter("date");

		if(date == null || date.length() == 0) {
			//SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
			date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());			
		}
		request.setAttribute("DATE", new SimpleDateFormat("yyyy-MM-dd E").format( new SimpleDateFormat("yyyy-MM-dd").parse(date) ));

		Map map = new TreeMap();
		map.put("date", date);


		try {
			UserWeekAttitude weekAttitude = weekAttitudeManager.getWeekAttitude(user.getUid().toString(), date);

			request.setAttribute("PARA", map);
			request.setAttribute("USER_WEEK_ATTITUDE", weekAttitude);

			return mapping.findForward("list");
		} catch (Exception e) {
			e.printStackTrace();
			return mapping.findForward("fail");
		}
	}

	
	
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {

		UcMembers user = (UcMembers) request.getSession()
				.getAttribute("CLIENT");

		String id = request.getParameter("id");
		String date = request.getParameter("date");
		
		// 22种积极心态
		String confident = request.getParameter("confident");
		String intent = request.getParameter("intent");
				
		SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");

		try {
			if(id !=null && id.length() >0) {
				UserWeekAttitude attitude = weekAttitudeManager.getWeekAttitude(Integer.parseInt(id));
				attitude.setUserId(user.getUid());
				attitude.setDate(dateFormatter.parse(date));
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				if(confident.equals("Y")) 
					attitude.setConfident("Y");
				else
					attitude.setConfident("N");
				
				
				
						
				weekAttitudeManager.updateWeekAttitude(attitude);
			}
			else {
				UserWeekAttitude attitude = new UserWeekAttitude();
				attitude.setUserId(user.getUid());
				attitude.setDate(dateFormatter.parse(date));

				
				weekAttitudeManager.addWeekAttitude(attitude);
			}
			
			request.setAttribute("OK_MESSAGE", "操作成功");
			request.setAttribute("RETURN_URL", "ClientManageUserDailySumup.do?act=list&date=" + date);
			
			return mapping.findForward("ok");
		} catch (Exception e) {
			e.printStackTrace();
			return mapping.findForward("fail");
		}
	}

	
}