/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.client;

import java.util.Date;

import com.forbes.hibernate.bean.UcMembers;
import com.forbes.hibernate.bean.User;
import com.forbes.mail.SendMailToRegister;
import com.forbes.service.client.ClientRegister;
import com.forbes.service.ucenter.UCenterManager;
import com.forbes.service.user.UserLogin;
import com.forbes.struts.form.user.UserRegisterForm;
import com.forbes.util.MD5;
import com.forbes.util.PasswordGenerator;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;



/** 
 * MyEclipse Struts
 * Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * @struts.action path="/client/ClientRegister" name="clientRegisterForm" attribute="ClientRegisterForm" input="/client/ClientRegister.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/user/UserRegisterOk.jsp"
 * @struts.action-forward name="fail" path="/user/UserRegister.jsp"
 */
public class ClientRegisterAction extends Action {
	/*#com.she.web.form.client.ClientRegisterForm Dependency20*/
/*
	 * Generated Methods
	 */

	ClientRegister clientRegister;
	
	

	public ClientRegister getClientRegister() {
		return clientRegister;
	}

	public void setClientRegister(ClientRegister clientRegister) {
		this.clientRegister = clientRegister;
	}



	/** 
	 * 客戶注冊
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserRegisterForm userRegisterForm = (UserRegisterForm) form;
		/*System.out.println("loginName="+userRegisterForm.getLoginName());
		System.out.println("password="+userRegisterForm.getPassword());
		System.out.println("eamil="+userRegisterForm.getEmail());
		System.out.println("Code="+userRegisterForm.getValidateCode());*/
		String salt = PasswordGenerator.genRandomNum(6);
		UcMembers user = new UcMembers();
		user.setUsername(userRegisterForm.getLoginName());
		user.setSalt(salt);
		user.setPassword(MD5.convert( MD5.convert(userRegisterForm.getPassword()) + salt ));
		//user.setActive("N");
		//user.setName(userRegisterForm.getName());
		user.setEmail(userRegisterForm.getEmail());
		//user.setScores(Integer.parseInt("0"));
		
		try {

			HttpSession session = request.getSession();
			String validateCode = (String) session.getAttribute("VALIDATE_CODE");
			session.removeAttribute("VALIDATE_CODE");
			
		
			if (!userRegisterForm.getValidateCode().equals(validateCode)) {
				request.setAttribute("CLIENT", user);
				request.setAttribute("ERROR_VALIDATE_CODE", "验证码错误，请重新输入。");
				return mapping.findForward("fail");
			} else {
				
				String checkLoginNameRs = clientRegister.checkLoginName(user.getUsername());
				if( !checkLoginNameRs.equals("OK") ){
					request.setAttribute("CLIENT", user);
					request.setAttribute("ERROR_LOGIN_NAME", checkLoginNameRs );
					return mapping.findForward("fail");
				}
				else {
					
					
					user.setRegip(request.getRemoteAddr());
					user.setRegdate(Integer.parseInt(String.valueOf(new Date().getTime()).substring(0, 10)));
					user.setLastloginip(0);
					user.setLastlogintime(0);
					
					clientRegister.register(user);
					
					//同步ucneter注册
					//UCenterManager uc = new UCenterManager();
					//uc.register(user, userRegisterForm.getPassword());
					
					request.setAttribute("CLIENT", user);
					return mapping.findForward("ok");
				}
			}			
			
		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("CLIENT", user);
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
		
		
	}

	
}