/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.client;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.hibernate.bean.Article;
import com.forbes.hibernate.bean.Content;
import com.forbes.hibernate.bean.UcMembers;
import com.forbes.hibernate.bean.UserDailyPlan;
import com.forbes.service.plan.DailyPlanManager;
import com.forbes.util.Pager;
import com.forbes.util.UrlTool;

/**
 * MyEclipse Struts Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/client/ClientLogin" name="clientLoginForm"
 *                attribute="ClientLoginForm" input="/client/ClientLogin.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/client/ClientLoginOk.jsp"
 * @struts.action-forward name="fail" path="/client/ClientLoginFail.jsp"
 */
public class ClientManageUserDailyPlanAction extends DispatchAction {
	/* #com.she.web.form.client.ClientLoginForm Dependency20 */
	/*
	 * Generated Methods
	 */

	private DailyPlanManager dailyPlanManager;


	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {

		UcMembers user = (UcMembers) request.getSession()
				.getAttribute("CLIENT");

		String pageNo = request.getParameter("pno");
		String keyword = request.getParameter("keyword");
		String iscomplete = request.getParameter("iscomplete");
		String date = request.getParameter("date");
		String orderby = request.getParameter("orderby");

		
		if(date == null || date.length() == 0) {
			SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
			date = formatter.format(new Date());
		}

		// System.out.println("----------favType:" + favType);

		String parameter = "keyword=" + ((keyword == null) ? " " : keyword)
				+ "iscomplete=" + ((iscomplete == null) ? " " : iscomplete)
				+ "date=" + ((date == null) ? " " : date)
				+ "orderby=" + ((orderby == null) ? " " : orderby);

		Map map = new TreeMap();
		map.put("keyword", keyword);
		map.put("iscomplete", iscomplete);
		map.put("date", date);
		map.put("orderby", orderby);

		int iPageNo = 1;
		try {
			iPageNo = Integer.parseInt(pageNo);
		} catch (Exception e) {

		}

		try {
			Pager pager = new Pager();
			pager.setCntOfPage(10);
			pager.setCurPage(iPageNo);

			List plans = dailyPlanManager.getDailyPlanByPage(pager, iPageNo,
					user.getUid().toString(), date, iscomplete, keyword,
					orderby);

			request.setAttribute("PARA", map);
			request.setAttribute("USER_PLAN_LIST", plans);
			request.setAttribute("PAGER", pager);

			return mapping.findForward("list");
		} catch (Exception e) {
			e.printStackTrace();
			return mapping.findForward("fail");
		}
	}

	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {

		UcMembers user = (UcMembers) request.getSession()
				.getAttribute("CLIENT");

		String title = request.getParameter("title");
		String date = request.getParameter("date");
		String limitTime = request.getParameter("limit_time");
		String startTimeHh = request.getParameter("start_time_hh");
		String startTimeMm = request.getParameter("start_time_mm");
		
		String endTimeHh = request.getParameter("end_time_hh");
		String endTimeMm = request.getParameter("end_time_mm");
		
		String content = request.getParameter("content");
		String isComplete = request.getParameter("is_complete");
		
		
		SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		SimpleDateFormat timeFormatter = new SimpleDateFormat("HH:mm:ss");
		SimpleDateFormat fullFormatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

		try {
			UserDailyPlan plan = new UserDailyPlan();
			plan.setUserId(user.getUid());
			plan.setDate(dateFormatter.parse(date));
			plan.setTitle(title);
			plan.setContent(content);
			plan.setStartTime(timeFormatter.parse(startTimeHh +":" + startTimeMm +":00"));
			plan.setEndTime(timeFormatter.parse(endTimeHh +":" + endTimeMm +":00"));
			
			if(limitTime !=null && limitTime.length() >0)
				plan.setLimitTime(fullFormatter.parse(limitTime));
			plan.setIsComplete(new Short(isComplete));
			plan.setSn(0);
			
			dailyPlanManager.addDailyPlan(plan);
			
			request.setAttribute("RETURN_URL", "ClientAddUserDailyPlan.jsp");
			
			return mapping.findForward("return");
		} catch (Exception e) {
			e.printStackTrace();
			return mapping.findForward("fail");
		}
	}
	
	public ActionForward edit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {

		String id = request.getParameter("id");
		String title = request.getParameter("title");
		String date = request.getParameter("date");
		String limitTime = request.getParameter("limit_time");
		String startTimeHh = request.getParameter("start_time_hh");
		String startTimeMm = request.getParameter("start_time_mm");
		
		String endTimeHh = request.getParameter("end_time_hh");
		String endTimeMm = request.getParameter("end_time_mm");
		
		String content = request.getParameter("content");
		String isComplete = request.getParameter("is_complete");
		
		
		SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		SimpleDateFormat timeFormatter = new SimpleDateFormat("HH:mm:ss");
		SimpleDateFormat fullFormatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

		try {
			UserDailyPlan plan = dailyPlanManager.getDailyPlan(Integer.parseInt(id));
			plan.setDate(dateFormatter.parse(date));
			plan.setTitle(title);
			plan.setContent(content);
			plan.setStartTime(timeFormatter.parse(startTimeHh +":" + startTimeMm +":00"));
			plan.setEndTime(timeFormatter.parse(endTimeHh +":" + endTimeMm +":00"));
			if(limitTime !=null && limitTime.length() >0)
				plan.setLimitTime(fullFormatter.parse(limitTime));
			plan.setIsComplete(new Short(isComplete));
			plan.setSn(0);
			
			dailyPlanManager.updateDailyPlan(plan);
			
			request.setAttribute("RETURN_URL", "ClientManageUserDailyPlan.do?act=edit&id="+id);
			
			return mapping.findForward("return");
		} catch (Exception e) {
			e.printStackTrace();
			return mapping.findForward("fail");
		}
	}
	
	public ActionForward complete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {

		String id = request.getParameter("id");
		String isComplete = request.getParameter("is_complete");

		try {
			UserDailyPlan plan = dailyPlanManager.getDailyPlan(Integer.parseInt(id));
			plan.setIsComplete(new Short(isComplete));
			
			dailyPlanManager.updateDailyPlan(plan);
			request.setAttribute("RESULT_MESSAGE", "OK");
			
			return mapping.findForward("ok");
		} catch (Exception e) {
			e.printStackTrace();
			request.setAttribute("RESULT_MESSAGE", "FAIL");
			return mapping.findForward("ok");
			
		}
	}

	public DailyPlanManager getDailyPlanManager() {
		return dailyPlanManager;
	}

	public void setDailyPlanManager(DailyPlanManager dailyPlanManager) {
		this.dailyPlanManager = dailyPlanManager;
	}

	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//String returnUrl = request.getParameter("returnUrl");
		String planID     = request.getParameter("planID");
		String id = ""; //`
		System.out.println(planID);
		String planIDs [] = planID.split("`");
		try {
			for(int i=0; i<planIDs.length; i++) {
				id = planIDs[i];
				System.out.println(id);
				UserDailyPlan plan = dailyPlanManager.getDailyPlan(Integer.parseInt(id));
				dailyPlanManager.deleteDailyPlan(plan);
			}
			request.setAttribute("RESULT_MESSAGE", "OK");
			return mapping.findForward("ok");
		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("RESULT_MESSAGE", "FAIL");
			return mapping.findForward("ok");
		}
	}
	
	public ActionForward get(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//String returnUrl = request.getParameter("returnUrl");
		String id = request.getParameter("id");

		try {
			UserDailyPlan plan = dailyPlanManager.getDailyPlan(Integer.parseInt(id));
			request.setAttribute("USER_DETAILY_PLAN", plan);
			return mapping.findForward("get");
		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("RESULT_MESSAGE", "FAIL");
			return mapping.findForward("ok");
		}
	}
}