/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.client;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.hibernate.bean.UcMembers;
import com.forbes.service.ucenter.UCenterManager;


/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class ClientLogoutAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	
	
	
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		UcMembers client = (UcMembers)request.getSession().getAttribute("CLIENT");
		
		try {
			if( client != null ) {
				//request.getSession().removeAttribute("CLIENT");
				request.getSession().invalidate();
				
				//清除cookie
				try {
					
					Cookie cookie = new Cookie("FORBES", null);
					cookie.setMaxAge(0); //设置为0为立即删除该Cookie
					//cookie.setPath("/test/test2"); //删除指定路径上的Cookie，不设置该路径，默认为删除当前路径Cookie
					response.addCookie(cookie);
					
				
				} catch(Exception e) {
					e.printStackTrace();
				}
				
				
				//同步ucneter登录
				UCenterManager uc = new UCenterManager();
				String syslogScript = uc.synLogout( client );
				//String syslogScript = uc.synLogout( client );
			    request.setAttribute("SYN_LGIN", syslogScript );
				
			}
				
			return mapping.findForward("logout");

		}catch( Exception e ){			
			//System.out.println(e.getMessage());
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}

	}
	
	public ActionForward index(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		UcMembers client = (UcMembers)request.getSession().getAttribute("CLIENT");
		
		try {
			if( client != null ) {
				//request.getSession().removeAttribute("CLIENT");
				request.getSession().invalidate();
				
				//清除cookie
				try {
					
					Cookie cookie = new Cookie("FORBES", null);
					cookie.setMaxAge(0); //设置为0为立即删除该Cookie
					//cookie.setPath("/test/test2"); //删除指定路径上的Cookie，不设置该路径，默认为删除当前路径Cookie
					response.addCookie(cookie);
					
				
				} catch(Exception e) {
					e.printStackTrace();
				}
				
				
				//同步ucneter登录
				UCenterManager uc = new UCenterManager();
				String syslogScript = uc.synLogout( client );
				//String syslogScript = uc.synLogout( client );
			    request.setAttribute("SYN_LGIN", syslogScript );
				
			}
				
			return mapping.findForward("index");

		}catch( Exception e ){			
			//System.out.println(e.getMessage());
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}

	}
	
}