/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.form.client;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;



/** 
 * MyEclipse Struts
 * Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * @struts.form name="ClientLoginForm"
 */
public class ClientModifyProfileForm extends ActionForm {
	
	private Integer id;
	private String name;
	private String sex;
	private String sexLock;
	private String email;
	private String emailLock;
	private String qq;
	private String qqLock;
	private String msn;
	private String msnLock;
	private Integer scores;
	private String birthType;
	private String birthLock;
	private Short birthYear;
	private Short birthMonth;
	private Short birthDay;
	private String homeLock;
	private Integer homeProvinceId;
	private String homeProvinceName;
	private Integer homeCityId;
	private String homeCityName;
	private Integer homeDistrictId;
	private String homeDistrictName;
	private String liveLock;
	private Integer liveProvinceId;
	private String liveProvinceName;
	private Integer liveCityId;
	private String liveCityName;
	private Integer liveDistrictId;
	private String liveDistrictName;
	private String phone;
	private String phoneLock;
	private String mobile;
	private String mobileLock;
	private Integer calling;
	private String callingLock;
	private Integer work;
	private String workLock;
	private String description;
	
	/*
	 * Generated Methods
	 */
	

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getSexLock() {
		return sexLock;
	}

	public void setSexLock(String sexLock) {
		this.sexLock = sexLock;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmailLock() {
		return emailLock;
	}

	public void setEmailLock(String emailLock) {
		this.emailLock = emailLock;
	}

	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getQqLock() {
		return qqLock;
	}

	public void setQqLock(String qqLock) {
		this.qqLock = qqLock;
	}

	public String getMsn() {
		return msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}

	public String getMsnLock() {
		return msnLock;
	}

	public void setMsnLock(String msnLock) {
		this.msnLock = msnLock;
	}

	public Integer getScores() {
		return scores;
	}

	public void setScores(Integer scores) {
		this.scores = scores;
	}

	public String getBirthType() {
		return birthType;
	}

	public void setBirthType(String birthType) {
		this.birthType = birthType;
	}

	public String getBirthLock() {
		return birthLock;
	}

	public void setBirthLock(String birthLock) {
		this.birthLock = birthLock;
	}

	public Short getBirthYear() {
		return birthYear;
	}

	public void setBirthYear(Short birthYear) {
		this.birthYear = birthYear;
	}

	public Short getBirthMonth() {
		return birthMonth;
	}

	public void setBirthMonth(Short birthMonth) {
		this.birthMonth = birthMonth;
	}

	public Short getBirthDay() {
		return birthDay;
	}

	public void setBirthDay(Short birthDay) {
		this.birthDay = birthDay;
	}

	public String getHomeLock() {
		return homeLock;
	}

	public void setHomeLock(String homeLock) {
		this.homeLock = homeLock;
	}

	public Integer getHomeProvinceId() {
		return homeProvinceId;
	}

	public void setHomeProvinceId(Integer homeProvinceId) {
		this.homeProvinceId = homeProvinceId;
	}

	public String getHomeProvinceName() {
		return homeProvinceName;
	}

	public void setHomeProvinceName(String homeProvinceName) {
		this.homeProvinceName = homeProvinceName;
	}

	public Integer getHomeCityId() {
		return homeCityId;
	}

	public void setHomeCityId(Integer homeCityId) {
		this.homeCityId = homeCityId;
	}

	public String getHomeCityName() {
		return homeCityName;
	}

	public void setHomeCityName(String homeCityName) {
		this.homeCityName = homeCityName;
	}

	public Integer getHomeDistrictId() {
		return homeDistrictId;
	}

	public void setHomeDistrictId(Integer homeDistrictId) {
		this.homeDistrictId = homeDistrictId;
	}

	public String getHomeDistrictName() {
		return homeDistrictName;
	}

	public void setHomeDistrictName(String homeDistrictName) {
		this.homeDistrictName = homeDistrictName;
	}

	public String getLiveLock() {
		return liveLock;
	}

	public void setLiveLock(String liveLock) {
		this.liveLock = liveLock;
	}

	public Integer getLiveProvinceId() {
		return liveProvinceId;
	}

	public void setLiveProvinceId(Integer liveProvinceId) {
		this.liveProvinceId = liveProvinceId;
	}

	public String getLiveProvinceName() {
		return liveProvinceName;
	}

	public void setLiveProvinceName(String liveProvinceName) {
		this.liveProvinceName = liveProvinceName;
	}

	public Integer getLiveCityId() {
		return liveCityId;
	}

	public void setLiveCityId(Integer liveCityId) {
		this.liveCityId = liveCityId;
	}

	public String getLiveCityName() {
		return liveCityName;
	}

	public void setLiveCityName(String liveCityName) {
		this.liveCityName = liveCityName;
	}

	public Integer getLiveDistrictId() {
		return liveDistrictId;
	}

	public void setLiveDistrictId(Integer liveDistrictId) {
		this.liveDistrictId = liveDistrictId;
	}

	public String getLiveDistrictName() {
		return liveDistrictName;
	}

	public void setLiveDistrictName(String liveDistrictName) {
		this.liveDistrictName = liveDistrictName;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPhoneLock() {
		return phoneLock;
	}

	public void setPhoneLock(String phoneLock) {
		this.phoneLock = phoneLock;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getMobileLock() {
		return mobileLock;
	}

	public void setMobileLock(String mobileLock) {
		this.mobileLock = mobileLock;
	}

	public Integer getCalling() {
		return calling;
	}

	public void setCalling(Integer calling) {
		this.calling = calling;
	}

	public String getCallingLock() {
		return callingLock;
	}

	public void setCallingLock(String callingLock) {
		this.callingLock = callingLock;
	}

	public Integer getWork() {
		return work;
	}

	public void setWork(Integer work) {
		this.work = work;
	}

	public String getWorkLock() {
		return workLock;
	}

	public void setWorkLock(String workLock) {
		this.workLock = workLock;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		//errors.add("loginName.value", new ActionMessage(loginName, false));
		//errors.add("password.value", new ActionMessage(password, false));
		
		/*request.setAttribute("LOGIN_NAME", loginName);
		request.setAttribute("PASSWORD", password);
		
		if ( loginName == null || loginName.length() < 1 ){
			errors.add("loginName.error", new ActionMessage("请输入用户名", false));
		}

		if ( password == null || password.length() < 1 ){
			errors.add("password.error", new ActionMessage("请输入密碼", false));
		}
		
		if ( validateFlag != null && validateFlag.equals("Y") ){
			if ( validateCode == null || validateCode.length() < 1 ){
				errors.add("validateCode", new ActionMessage("请输入验证码", false));
			}
			else {
				HttpSession session = request.getSession();
				String checkCode = (String) session.getAttribute("VALIDATE_CODE");
				session.removeAttribute("VALIDATE_CODE");
				
				if (!request.getParameter("validateCode").equals(checkCode)) {
					errors.add("validateCode.error", new ActionMessage("验证碼错误，請重新登錄。", false));
					//request.setAttribute("ERROR_INFO", "验证碼错误，請重新登錄。");
				}
			}
		}*/
		
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}


	

}