/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.form.client;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;



/** 
 * MyEclipse Struts
 * Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * @struts.form name="ClientLoginForm"
 */
public class ClientUserWeekAbilityForm extends ActionForm {
	
	
	private Integer id;
	private Integer userId;
	private String date;
	private String ardour;
	private String promises;
	private String responsibility;
	private String admire;
	private String contribute;
	private String believe;
	private String winwin;
	private String listen;
	private String focus;
	private String echo;
	private String praise;
	private String convince;
	private String feedback;
	private String thank;
	private String visualize;
	private String study;
	private String innovation;
	private String love;
	private String gumption;
	private String purpose;
	private String intent;
	private String professional;
	private String willpower;
	
	/*
	 * Generated Methods
	 */
	

	

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		//ActionErrors errors = new ActionErrors();		
		
		if ( ardour == null || ardour.length() < 1 ){
			setArdour("N");
		}
		
		if ( intent == null || intent.length() < 1 ){
			setIntent("N");
		}
		
		if ( promises == null || promises.length() < 1 ){
			setPromises("N");
		}
		
		if ( responsibility == null || responsibility.length() < 1 ){
			setResponsibility("N");
		}
		
		if ( love == null || love.length() < 1 ){
			setLove("N");
		}
		
		if ( study == null || study.length() < 1 ){
			setStudy("N");
		}
		
		if ( admire == null || admire.length() < 1 ){
			setAdmire("N");
		}
		
		if ( contribute == null || contribute.length() < 1 ){
			setContribute("N");
		}
		
		if ( believe == null || believe.length() < 1 ){
			setBelieve("N");
		}
		
		if ( winwin == null || winwin.length() < 1 ){
			setWinwin("N");
		}
		
		if ( listen == null || listen.length() < 1 ){
			setListen("N");
		}
		
		if ( focus == null || focus.length() < 1 ){
			setFocus("N");
		}
		
		if ( echo == null || echo.length() < 1 ){
			setEcho("N");
		}
		
		if ( praise == null || praise.length() < 1 ){
			setPraise("N");
		}
		
		if ( responsibility == null || responsibility.length() < 1 ){
			setResponsibility("N");
		}
		
		if ( convince == null || convince.length() < 1 ){
			setConvince("N");
		}
		
		if ( feedback == null || feedback.length() < 1 ){
			setFeedback("N");
		}
		
		if ( thank == null || thank.length() < 1 ){
			setThank("N");
		}
		
		if ( purpose == null || purpose.length() < 1 ){
			setPurpose("N");
		}
		
		if ( visualize == null || visualize.length() < 1 ){
			setVisualize("N");
		}
		
		if ( study == null || study.length() < 1 ){
			setStudy("N");
		}
		
		if ( innovation == null || innovation.length() < 1 ){
			setInnovation("N");
		}
			
		if ( love == null || love.length() < 1 ){
			setLove("Y");
		}
		
		if ( gumption == null || gumption.length() < 1 ){
			setGumption("Y");
		}
		
		if ( purpose == null || purpose.length() < 1 ){
			setPurpose("Y");
		}
		
		if ( intent == null || intent.length() < 1 ){
			setIntent("Y");
		}
		
		if ( professional == null || professional.length() < 1 ){
			setProfessional("Y");
		}
		
		if ( willpower == null || willpower.length() < 1 ){
			setWillpower("Y");
		}
		
	
		
		//return errors;
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getArdour() {
		return ardour;
	}

	public void setArdour(String ardour) {
		this.ardour = ardour;
	}

	public String getPromises() {
		return promises;
	}

	public void setPromises(String promises) {
		this.promises = promises;
	}

	public String getResponsibility() {
		return responsibility;
	}

	public void setResponsibility(String responsibility) {
		this.responsibility = responsibility;
	}

	public String getAdmire() {
		return admire;
	}

	public void setAdmire(String admire) {
		this.admire = admire;
	}

	public String getContribute() {
		return contribute;
	}

	public void setContribute(String contribute) {
		this.contribute = contribute;
	}

	public String getBelieve() {
		return believe;
	}

	public void setBelieve(String believe) {
		this.believe = believe;
	}

	public String getWinwin() {
		return winwin;
	}

	public void setWinwin(String winwin) {
		this.winwin = winwin;
	}

	public String getListen() {
		return listen;
	}

	public void setListen(String listen) {
		this.listen = listen;
	}

	public String getFocus() {
		return focus;
	}

	public void setFocus(String focus) {
		this.focus = focus;
	}

	public String getEcho() {
		return echo;
	}

	public void setEcho(String echo) {
		this.echo = echo;
	}

	public String getPraise() {
		return praise;
	}

	public void setPraise(String praise) {
		this.praise = praise;
	}

	public String getConvince() {
		return convince;
	}

	public void setConvince(String convince) {
		this.convince = convince;
	}

	public String getFeedback() {
		return feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	public String getThank() {
		return thank;
	}

	public void setThank(String thank) {
		this.thank = thank;
	}

	public String getVisualize() {
		return visualize;
	}

	public void setVisualize(String visualize) {
		this.visualize = visualize;
	}

	public String getStudy() {
		return study;
	}

	public void setStudy(String study) {
		this.study = study;
	}

	public String getInnovation() {
		return innovation;
	}

	public void setInnovation(String innovation) {
		this.innovation = innovation;
	}

	public String getLove() {
		return love;
	}

	public void setLove(String love) {
		this.love = love;
	}

	public String getGumption() {
		return gumption;
	}

	public void setGumption(String gumption) {
		this.gumption = gumption;
	}

	public String getPurpose() {
		return purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public String getIntent() {
		return intent;
	}

	public void setIntent(String intent) {
		this.intent = intent;
	}

	public String getProfessional() {
		return professional;
	}

	public void setProfessional(String professional) {
		this.professional = professional;
	}

	public String getWillpower() {
		return willpower;
	}

	public void setWillpower(String willpower) {
		this.willpower = willpower;
	}

}