/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.index;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.hibernate.bean.UchomeFeed;
import com.forbes.service.ucenter.UchomeManager;
import com.forbes.util.Constant;

/** 
 * MyEclipse Struts
 * Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * @struts.action path="/client/ClientLogin" name="clientLoginForm" attribute="ClientLoginForm" input="/client/ClientLogin.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/client/ClientLoginOk.jsp"
 * @struts.action-forward name="fail" path="/client/ClientLoginFail.jsp"
 */
public class GetTopUchomeFeedAction extends Action {
	/*#com.forbes.web.form.client.ClientLoginForm Dependency20*/
	/*
	 * Generated Methods
	 */
   private UchomeManager uchomeManager;
	/** 
	 * ¿Í»§µÇä›
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		
		List list = uchomeManager.getUchomeFeeds(null, 0, 14);
		List sl   = null;
		String temp;
		for(int i=0; i<list.size(); i++) {
			UchomeFeed feed = (UchomeFeed)list.get(i);
			temp = feed.getTitleTemplate();
			temp = temp.replace("{actor}", "<a href='" + Constant.UC_URL +"/home/space.php?uid=" + feed.getUid() + "'>" +feed.getUsername() + "</a>");
			//System.out.println(temp);
		}
		request.setAttribute("UC_HOME_FEED_LIST", list);
		
		//System.out.println("content = " + content);
		return mapping.findForward("ok");
	}
	
	public UchomeManager getUchomeManager() {
		return uchomeManager;
	}
	public void setUchomeManager(UchomeManager uchomeManager) {
		this.uchomeManager = uchomeManager;
	}
	
   

	


}