/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.index;

import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.service.article.ArticleListManager;

/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class IndexArticleListAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	
	private ArticleListManager articleListManager;
	
	public ArticleListManager getArticleListManager() {
		return articleListManager;
	}

	public void setArticleListManager(ArticleListManager articleListManager) {
		this.articleListManager = articleListManager;
	}
	
	public ActionForward commend(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//System.out.println(" top ten article list...");

		String typeid  = request.getParameter("typeid");
		String orderby = request.getParameter("orderby");
		if( orderby == null)
			orderby = "pubdate DESC";
		try {
			
			List list = articleListManager.getTopArticleByArticleType(typeid, orderby, 0, 10);

			request.setAttribute( "ARTICLE_LIST", list);
			//System.out.println(list.size());
			
			return mapping.findForward("commend");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public ActionForward hot(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//System.out.println(" hot ten article list...");

		String typeid  = request.getParameter("typeid");
		String orderby = request.getParameter("orderby");
		if( orderby == null)
			orderby = "iscommend DESC";
		try {
			
			List list = articleListManager.getTopArticleByArticleType(typeid, orderby, 0, 6);

			request.setAttribute( "ARTICLE_LIST", list);
			//System.out.println(list.size());
			
			return mapping.findForward("hot");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
}