/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.index;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.service.ucenter.UcbbsManager;
import com.forbes.service.ucenter.UchomeManager;
import com.forbes.util.Constant;

/** 
 * MyEclipse Struts
 * Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * @struts.action path="/client/ClientLogin" name="clientLoginForm" attribute="ClientLoginForm" input="/client/ClientLogin.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/client/ClientLoginOk.jsp"
 * @struts.action-forward name="fail" path="/client/ClientLoginFail.jsp"
 */
public class GetTopCdbForumsAction extends Action {
	/*#com.forbes.web.form.client.ClientLoginForm Dependency20*/
	/*
	 * Generated Methods
	 */
   private UcbbsManager ucbbsManager;
	/** 
	 * ¿Í»§µÇä›
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		
		String fup     = "1";
		String type    = "forum";
		String status  = "1";
		String orderby = "threads";
		List list = ucbbsManager.getCdbForums(fup, type, status, orderby, 0, 14);
		request.setAttribute("UC_BBS_FORUM_LIST", list);
		
		//System.out.println("content = " + content);
		return mapping.findForward("ok");
	}
	
	public UcbbsManager getUcbbsManager() {
		return ucbbsManager;
	}
	public void setUcbbsManager(UcbbsManager ucbbsManager) {
		this.ucbbsManager = ucbbsManager;
	}
	

   

	


}