/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.index;

import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.service.ask.AskSearchManager;
import com.forbes.service.video.VideoListManager;


/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class IndexAskListAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	//private VideoTypeManager videoTypeManager;
	
	private AskSearchManager askSearchManager;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward commend(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//System.out.println(" top video list...");
		
		try {
			
			List list = askSearchManager.getTopAsk(null, null, "views DESC", 0, 10);
			
			//(String typeid, String status, String orderby, int beg, int len) {

			request.setAttribute( "ASK_LIST", list);
			//System.out.println(list.size());
			
			return mapping.findForward("commend");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	
	public ActionForward hot(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//System.out.println(" top video list...");
		
		try {
			
			List list = askSearchManager.getTopAsk(null, null, "views DESC", 0, 6);

			request.setAttribute( "ASK_LIST", list);
			//System.out.println(list.size());
			
			return mapping.findForward("hot");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}


	public AskSearchManager getAskSearchManager() {
		return askSearchManager;
	}


	public void setAskSearchManager(AskSearchManager askSearchManager) {
		this.askSearchManager = askSearchManager;
	}

	
	
	
	
	
}