/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.index;

import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.service.article.ArticleListManager;
import com.forbes.service.article.NewsManager;
import com.forbes.service.ask.AskSearchManager;
import com.forbes.service.ucenter.UcbbsManager;
import com.forbes.service.ucenter.UchomeManager;
import com.forbes.service.user.UserInfoManager;
import com.forbes.service.video.VideoListManager;


/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class IndexAction extends Action {
	/*
	 * Generated Methods
	 */
	//private VideoTypeManager videoTypeManager;
	
	private VideoListManager videoListManager;
	
	private ArticleListManager articleListManager;
	
	private AskSearchManager askSearchManager;
	
	private NewsManager newsManager;
	
	private UserInfoManager userInfoManager;
	
	// bbs home
	private UchomeManager uchomeManager;
	
	private UcbbsManager ucbbsManager;
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
				
		try {

			//video 
			request.setAttribute( "HOT_VIDEO_LIST", videoListManager.getTopVideoByVideoType(null, "iscommend DESC", 0, 10));
			request.setAttribute( "NEW_VIDEO_LIST", videoListManager.getTopVideoByVideoType(null, "pubdate DESC", 0, 10));
			
			//article
			request.setAttribute( "ARTICLE_01_LIST", articleListManager.getTopArticleByArticleType("1", "pubdate DESC", 0, 10));
			request.setAttribute( "ARTICLE_26_LIST", articleListManager.getTopArticleByArticleType("26", "pubdate DESC", 0, 10));
			request.setAttribute( "ARTICLE_05_LIST", articleListManager.getTopArticleByArticleType("5", "pubdate DESC", 0, 10));
			request.setAttribute( "ARTICLE_11_LIST", articleListManager.getTopArticleByArticleType("11", "pubdate DESC", 0, 10));
			request.setAttribute( "ARTICLE_17_LIST", articleListManager.getTopArticleByArticleType("17", "pubdate DESC", 0, 10));
			request.setAttribute( "ARTICLE_10_LIST", articleListManager.getTopArticleByArticleType("10", "pubdate DESC", 0, 10));
			request.setAttribute( "ARTICLE_42_LIST", articleListManager.getTopArticleByArticleType("42", "pubdate DESC", 0, 10));
			request.setAttribute( "ARTICLE_43_LIST", articleListManager.getTopArticleByArticleType("43", "pubdate DESC", 0, 10));
			request.setAttribute( "ARTICLE_35_LIST", articleListManager.getTopArticleByArticleType("35", "pubdate DESC", 0, 10));
			request.setAttribute( "ARTICLE_16_LIST", articleListManager.getTopArticleByArticleType("16", "pubdate DESC", 0, 10));
			
			request.setAttribute( "HOT_ARTICLE_LIST", articleListManager.getTopArticleByArticleType(null, "iscommend DESC", 0, 6));
			
			
			//ask
			request.setAttribute( "ASK_LIST", askSearchManager.getTopAsk(null, null, "views DESC", 0, 6));
			
			//new
			request.setAttribute( "TOP_NEWS_LIST", newsManager.getTopNews("pubdate DESC", 1, 6));
			request.setAttribute( "FIRST_NEWS_LIST", newsManager.getTopNews("pubdate DESC", 0, 1));
			
			//user
			request.setAttribute( "USER_LIST", userInfoManager.getNewRegister(null, 0, 8));
			
			//home mtag
			request.setAttribute( "UC_HOME_MTAG_LIST", uchomeManager.getUchomeMtags(null, 0, 14));
			
			//home blog
			request.setAttribute( "UC_HOME_BLOG_LIST", uchomeManager.getUchomeBlogs("viewnum", 0, 7));

			//bbs forums
			String fup     = "1";
			String type    = "forum";
			String status  = "1";
			String orderby = "threads";
			request.setAttribute("UC_BBS_FORUM_LIST", ucbbsManager.getCdbForums(fup, type, status, orderby, 0, 14));
			
			//bbs thread
			request.setAttribute("UC_BBS_THREAD_LIST", ucbbsManager.getCdbThreads("views", 0, 14));
			
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	

	public VideoListManager getVideoListManager() {
		return videoListManager;
	}
	public void setVideoListManager(VideoListManager videoListManager) {
		this.videoListManager = videoListManager;
	}


	public ArticleListManager getArticleListManager() {
		return articleListManager;
	}


	public void setArticleListManager(ArticleListManager articleListManager) {
		this.articleListManager = articleListManager;
	}


	public AskSearchManager getAskSearchManager() {
		return askSearchManager;
	}


	public void setAskSearchManager(AskSearchManager askSearchManager) {
		this.askSearchManager = askSearchManager;
	}


	public NewsManager getNewsManager() {
		return newsManager;
	}


	public void setNewsManager(NewsManager newsManager) {
		this.newsManager = newsManager;
	}


	public UserInfoManager getUserInfoManager() {
		return userInfoManager;
	}


	public void setUserInfoManager(UserInfoManager userInfoManager) {
		this.userInfoManager = userInfoManager;
	}


	public UchomeManager getUchomeManager() {
		return uchomeManager;
	}


	public void setUchomeManager(UchomeManager uchomeManager) {
		this.uchomeManager = uchomeManager;
	}


	public UcbbsManager getUcbbsManager() {
		return ucbbsManager;
	}


	public void setUcbbsManager(UcbbsManager ucbbsManager) {
		this.ucbbsManager = ucbbsManager;
	}
	
	
	
	
}