/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.admin;

import java.util.List;
import java.util.Set;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.hibernate.bean.ArticleType;
import com.forbes.service.article.ArticleTypeManager;
import com.forbes.util.Pager;
import com.forbes.util.UrlTool;


/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class AdminUpdateArticleTypeAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private ArticleTypeManager articleTypeManager;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String pageNo    = request.getParameter("pno");
		
		int iPageNo = 1;
		try {
			if( pageNo != null ){
				iPageNo = Integer.parseInt( pageNo );
			}
		} catch( Exception e ){ }

		List list = null;
		Pager pager = new Pager();
		pager.setCntOfPage( 10 );
		pager.setCurPage( iPageNo );
		
		try {
		
			list = articleTypeManager.getTopArticleTypeByPage(pager, iPageNo);
			//List all = articleTypeManager.getTopArticleType();
			
			request.setAttribute( "PAGER", pager );
			//request.setAttribute( "TOP_ARTICLE_TYPE", all );
			request.setAttribute( "ARTICLE_TYPE_LIST", list);
			return mapping.findForward("list");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		String pid       	= request.getParameter("pid");
		String name      	= request.getParameter("name");
		String disorder  	= request.getParameter("disorder");
		String issend    	= request.getParameter("issend");
		String description  = request.getParameter("description");
		String keywords 	 = request.getParameter("keywords");
		String returnUrl 	= request.getParameter("returnUrl");
		
		try {
		
			if ( pid.equals("0")) {
				ArticleType c = new ArticleType();
				c.setName(name);
				c.setPid(0);
				c.setDisorder(Integer.parseInt(disorder));
				c.setIssend(issend);
				c.setDescription(description);
				c.setKeywords(keywords);
				articleTypeManager.addArticleType(c);
				request.setAttribute( "OK_MESSAGE", "添加文章类型成功！");
			}
			else {
				ArticleType c = new ArticleType();
				c.setName(name);
				c.setPid(Integer.parseInt(pid));
				c.setDisorder(Integer.parseInt(disorder));
				c.setIssend(issend);
				c.setDescription(description);
				c.setKeywords(keywords);
				articleTypeManager.addArticleType(c);
				request.setAttribute( "OK_MESSAGE", "添加文章类型成功！");
			}
			
			
			request.setAttribute( "RETURN_URL", new UrlTool().getUrl2(returnUrl, "[|]"));
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	
	public ActionForward modify(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		String id        = request.getParameter("id");
		String name      = request.getParameter("name");
		String disorder  = request.getParameter("disorder");
		String issend    	= request.getParameter("issend");
		String description  = request.getParameter("description");
		String keywords 	 = request.getParameter("keywords");
		String returnUrl = request.getParameter("returnUrl");
		
		try {
			
			ArticleType c = articleTypeManager.getArticleType(Integer.parseInt(id));
			
			c.setName(name);
			c.setDisorder(Integer.parseInt(disorder));
			c.setIssend(issend);
			c.setDescription(description);
			c.setKeywords(keywords);
			
			articleTypeManager.updateArticleType(c);
			request.setAttribute( "OK_MESSAGE", "修改文章类型成功！");			
			request.setAttribute( "RETURN_URL", new UrlTool().getUrl2(returnUrl, "[|]"));
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		String id       = request.getParameter("id");
		String returnUrl = request.getParameter("returnUrl");
		
		try {
		
			ArticleType c = articleTypeManager.getArticleType(Integer.parseInt(id));
			System.out.println( "cid=" + c.getId() + "\tcname=" + c.getName() + "\tcpid=" + c.getPid());
			if (c.getPid() == 0) {
				
				Set <ArticleType> articleTypes = c.getArticleTypes();
				for( ArticleType articleType : articleTypes ){
					System.out.println( "cityid=" + articleType.getId() + "\tcityname=" + articleType.getName() + "\tcitypid=" + articleType.getPid());
					articleTypeManager.deleteArticleType(articleType);
				}
				articleTypeManager.deleteArticleType(c);
				request.setAttribute( "OK_MESSAGE", "删除文章类型成功！");
			}
			else {
				
				articleTypeManager.deleteArticleType(c);
				request.setAttribute( "OK_MESSAGE", "删除文章类型成功！");
			}
			
			
			request.setAttribute( "RETURN_URL", new UrlTool().getUrl2(returnUrl, "[|]"));
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}

	public ArticleTypeManager getArticleTypeManager() {
		return articleTypeManager;
	}

	public void setArticleTypeManager(ArticleTypeManager articleTypeManager) {
		this.articleTypeManager = articleTypeManager;
	}

	
	public ActionForward get(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		String id        = request.getParameter("id");
		String returnUrl = request.getParameter("returnUrl");
		
		try {
			
			ArticleType c = articleTypeManager.getArticleType(Integer.parseInt(id));

			request.setAttribute( "ARTICLE_TYPE", c);
			request.setAttribute( "RETURN_URL", returnUrl);
			return mapping.findForward("get");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}


	public ActionForward move_get(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String id        = request.getParameter("id");
		String returnUrl = request.getParameter("returnUrl");

		try {
			ArticleType c = articleTypeManager.getArticleType(Integer.parseInt(id));
			List all = articleTypeManager.getArticleType();
			
			request.setAttribute( "ARTICLE_TYPE", c);
			request.setAttribute( "ARTICLE_TYPE_LIST", all );
			request.setAttribute( "RETURN_URL", returnUrl );
			return mapping.findForward("move_get");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	
	public ActionForward move(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String id        = request.getParameter("id").trim();
		String pid       = request.getParameter("pid").trim();
		String returnUrl = request.getParameter("returnUrl");
		
		if(id.equals(pid)) {
			request.setAttribute( "OK_MESSAGE", "移对对象和目标位置相同！！");
			request.setAttribute( "RETURN_URL", new UrlTool().getUrl2(returnUrl, "[|]") );
			return mapping.findForward("ok");
		}

		try {
			ArticleType c = articleTypeManager.getArticleType(Integer.parseInt(id));
			c.setPid(Integer.parseInt(pid));
			articleTypeManager.updateArticleType(c);
			
			request.setAttribute( "OK_MESSAGE", "移动文章类型成功！");
			request.setAttribute( "RETURN_URL", new UrlTool().getUrl2(returnUrl, "[|]") );
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
}