/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.admin;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.hibernate.bean.City;
import com.forbes.service.basic.CityManager;
import com.forbes.util.Pager;
import com.forbes.util.UrlTool;


/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class AdminUpdateCityAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private CityManager cityManager;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String pageNo    = request.getParameter("pno");
		
		int iPageNo = 1;
		try {
			if( pageNo != null ){
				iPageNo = Integer.parseInt( pageNo );
			}
		} catch( Exception e ){ }

		List list = null;
		Pager pager = new Pager();
		pager.setCntOfPage( 10 );
		pager.setCurPage( iPageNo );
		
		try {
		
			list = cityManager.getProvinceByPage(pager, iPageNo);
			List all = cityManager.getAllProvince();
			
			request.setAttribute( "PAGER", pager );
			request.setAttribute( "ALL_PROVINCE", all );
			request.setAttribute( "PROVINCE_LIST", list);
			return mapping.findForward("list");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		String pid       = request.getParameter("pid");
		String name      = request.getParameter("name");
		String returnUrl = request.getParameter("returnUrl");
		
		try {
		
			if ( pid.equals("0")) {
				City c = new City();
				c.setName(name);
				c.setPid(0);
				c.setDisorder(0);
				cityManager.addCity(c);
				request.setAttribute( "OK_MESSAGE", "添加一级地区成功！");
			}
			else {
				City c = new City();
				c.setName(name);
				c.setPid(Integer.parseInt(pid));
				c.setDisorder(0);
				cityManager.addCity(c);
				request.setAttribute( "OK_MESSAGE", "添加二级地区成功！");
			}
			
			
			request.setAttribute( "RETURN_URL", new UrlTool().getUrl2(returnUrl, "[|]"));
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	
	public ActionForward modify(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		String id        = request.getParameter("id");
		String name      = request.getParameter("name");
		String disorder  = request.getParameter("disorder");
		String returnUrl = request.getParameter("returnUrl");
		
		try {
			
			City c = cityManager.getCity(Integer.parseInt(id));
			
			c.setName(name);
			c.setDisorder(Integer.parseInt(disorder));
			
			cityManager.updateCity(c);
			request.setAttribute( "OK_MESSAGE", "修改地区成功！");			
			request.setAttribute( "RETURN_URL", new UrlTool().getUrl2(returnUrl, "[|]"));
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		String id       = request.getParameter("id");
		String returnUrl = request.getParameter("returnUrl");
		
		try {
		
			City c = cityManager.getCity(Integer.parseInt(id));
			System.out.println( "cid=" + c.getId() + "\tcname=" + c.getName() + "\tcpid=" + c.getPid());
			if (c.getPid() == 0) {
				
				Set <City>citys = c.getCitys();
				for( City city : citys ){
					System.out.println( "cityid=" + city.getId() + "\tcityname=" + city.getName() + "\tcitypid=" + city.getPid());
					cityManager.deleteCity(city);
				}
				cityManager.deleteCity(c);
				request.setAttribute( "OK_MESSAGE", "删除地区成功！");
			}
			else {
				
				cityManager.deleteCity(c);
				request.setAttribute( "OK_MESSAGE", "删除地区成功！");
			}
			
			
			request.setAttribute( "RETURN_URL", new UrlTool().getUrl2(returnUrl, "[|]"));
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public CityManager getCityManager() {
		return cityManager;
	}
	public void setCityManager(CityManager cityManager) {
		this.cityManager = cityManager;
	}




	
	
}