/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.admin;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.util.Constant;
import com.forbes.util.FileAccess;
import com.forbes.util.ToHtml;


/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class AdminTohtmlAction extends Action {
	/*
	 * Generated Methods
	 */
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String serviceIDs[] = request.getParameterValues("serviceID");

		for(int i=0; i<serviceIDs.length; i++) {
			
			String serviceID = serviceIDs[i];
			//生成静态页面
			System.out.println("serviceID=" + serviceID);
			try {
				if(serviceID.trim().equals("1")) {
										
					java.io.File myFilePath = new java.io.File(Constant.APPSERV_VIRTUAL_ADDRESS);

					if (!myFilePath.exists()) {
						myFilePath.mkdir();
					}					
					boolean flag = ToHtml.toHtml(Constant.FORBES_URL + "/NewIndex.do",
							Constant.APPSERV_VIRTUAL_ADDRESS + "\\index.html", "gbk", "gbk");
					FileAccess.Copy(Constant.APPSERV_VIRTUAL_ADDRESS + "\\index.html", 
							Constant.TOMCAT_VIRTUAL_ADDRESS + "\\index.html");
				}
				if(serviceID.trim().equals("2")) {					
					
					java.io.File myFilePath = new java.io.File(Constant.APPSERV_VIRTUAL_ADDRESS_ARTICLE);

					if (!myFilePath.exists()) {
						myFilePath.mkdir();
					}
					boolean flag = ToHtml.toHtml(Constant.FORBES_URL + "/article/NewIndex.do",
							Constant.APPSERV_VIRTUAL_ADDRESS_ARTICLE + "\\index.html", "gbk", "gbk");
					FileAccess.Copy(Constant.APPSERV_VIRTUAL_ADDRESS_ARTICLE + "\\index.html", 
							Constant.TOMCAT_VIRTUAL_ADDRESS_ARTICLE + "\\index.html");
				}
				if(serviceID.trim().equals("3")) {		
					
					java.io.File myFilePath = new java.io.File(Constant.APPSERV_VIRTUAL_ADDRESS_VIDEO);

					if (!myFilePath.exists()) {
						myFilePath.mkdir();
					}					
					boolean flag = ToHtml.toHtml(Constant.FORBES_URL + "/video/NewIndex.do",
							Constant.APPSERV_VIRTUAL_ADDRESS_VIDEO + "\\index.html", "gbk", "gbk");
					FileAccess.Copy(Constant.APPSERV_VIRTUAL_ADDRESS_VIDEO + "\\index.html", 
							Constant.TOMCAT_VIRTUAL_ADDRESS_VIDEO + "\\index.html");
				}
				if(serviceID.trim().equals("4")) {					
					
					java.io.File myFilePath = new java.io.File(Constant.APPSERV_VIRTUAL_ADDRESS_ASK);

					if (!myFilePath.exists()) {
						myFilePath.mkdir();
					}
					
					boolean flag = ToHtml.toHtml(Constant.FORBES_URL + "/ask/NewIndex.do",
							Constant.APPSERV_VIRTUAL_ADDRESS_ASK + "\\index.html", "gbk", "gbk");
					FileAccess.Copy(Constant.APPSERV_VIRTUAL_ADDRESS_ASK + "\\index.html", 
							Constant.TOMCAT_VIRTUAL_ADDRESS_ASK + "\\index.html");
				}
				
				
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		
		request.setAttribute( "OK_MESSAGE", "成功生成静态页面！" );
		request.setAttribute( "RETURN_URL", "to_html.jsp" );
		return mapping.findForward("ok");
	 	
	}
		
	
}