/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.admin;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.listener.ArticleImportStatus;
import com.forbes.listener.FileUploadStatus;

/** 
 * MyEclipse Struts
 * Creation date: 09-07-2009
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 * @struts.action-forward name="ok" path="/info.jsp"
 */
public class AdminImportArticleProgressAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		ArticleImportStatus status = (ArticleImportStatus) session.getAttribute("ARTICLE_IMPORT_STATUS");
		
			//response.reset();
			/*
			 * response.getWriter().write("{\"pBytesRead\":"
			 * +status.getPBytesRead()+",\"pContentLength\":"+status.getPContentLength()+"}");
			 */
		System.out.println("{\"pBytesRead\":"
				+status.getImportCnt()+",\"pContentLength\":"+status.getTotalCnt()+"}");
		request.setAttribute("MESSAGE", "{\"pBytesRead\":"
				+status.getImportCnt()+",\"pContentLength\":"+status.getTotalCnt()+"}");
		return mapping.findForward("ok");
	}
}