/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.admin;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.hibernate.bean.Article;
import com.forbes.hibernate.bean.ArticleContent;
import com.forbes.service.article.ArticleListManager;
import com.forbes.util.Constant;
import com.forbes.util.SysConfigManager;
import com.forbes.util.ToHtml;
import com.forbes.util.UrlTool;



/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class AdminCreateArticleHtmlAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private ArticleListManager articleListManager;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward all(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String returnUrl = request.getParameter("returnUrl");
		String fobresUrl = (String)SysConfigManager.getValue("cfg_forbes_url");
		
		boolean flag = false;
		int okCnt 	 = 0;
		int failCnt  = 0;
		try {
			List list = articleListManager.getAllArticleid();
			for(int i=0; i<list.size(); i++) {
				int articleid = (Integer)list.get(i);
				/*flag = ToHtml.toHtml(fobresUrl + "/article/ArticleView.do?id="+articleid,
						request.getRealPath("/") + "article" + "/" + articleid + ".html", "gbk", "gbk");*/
				
				//生成TXT文件
				//Article article = articleListManager.getArticle(articleid);
				ArticleContent content = articleListManager.getArticleContent(articleid);
				
				boolean txtFlag = ToHtml.toTxt(content.getContent(),
						request.getRealPath("/") + "article/txt/" + articleid + ".txt", "gbk");
				if(flag)
					okCnt++;
				else
					failCnt++;
			}
			request.setAttribute( "OK_MESSAGE", "成功生成" + okCnt + "个，失败" + failCnt + "个！" );
			request.setAttribute( "RETURN_URL", new UrlTool().getUrl2(returnUrl, "[|]") );
			return mapping.findForward("ok");
		} catch (Exception e) {
			e.printStackTrace();
			request.setAttribute( "FAIL_MESSAGE", "生成失败，请稍后再试。" );
			return mapping.findForward("fail");
		}
        
    }
	
	public ActionForward batch(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String returnUrl = request.getParameter("returnUrl");
		String arcID     = request.getParameter("arcID");
		String fobresUrl = (String)SysConfigManager.getValue("cfg_forbes_url");
		String id = ""; //`
		System.out.println(arcID);
		String artID [] = arcID.split("`");
		
		boolean flag = false;
		int okCnt 	 = 0;
		int failCnt  = 0;
		
		try {
		
			for(int i=0; i<artID.length; i++) {
				id = artID[i];
				System.out.println(id);
				flag = ToHtml.toHtml(fobresUrl + "/article/ArticleView.do?id="+id,
						request.getRealPath("/") + "article" + "/" + id + ".html", "gbk", "gbk");
				
				//Article article = articleListManager.getArticle(Integer.parseInt(id));
				ArticleContent content = articleListManager.getArticleContent(Integer.parseInt(id));
				boolean txtFlag = ToHtml.toTxt(content.getContent(),
						request.getRealPath("/") + "article/txt/" + id + ".txt", "gbk");
				
				if(flag)
					okCnt++;
				else
					failCnt++;
			}
			
			request.setAttribute( "OK_MESSAGE", "成功生成" + okCnt + "个，失败" + failCnt + "个！" );
			request.setAttribute( "RETURN_URL", new UrlTool().getUrl2(returnUrl, "[|]") );
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
        
    }
	public ArticleListManager getArticleListManager() {
		return articleListManager;
	}
	public void setArticleListManager(ArticleListManager articleListManager) {
		this.articleListManager = articleListManager;
	}

}