/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.ucenter;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.util.Constant;

/** 
 * MyEclipse Struts
 * Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * @struts.action path="/client/ClientLogin" name="clientLoginForm" attribute="ClientLoginForm" input="/client/ClientLogin.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/client/ClientLoginOk.jsp"
 * @struts.action-forward name="fail" path="/client/ClientLoginFail.jsp"
 */
public class GetUCenterInfoAction extends Action {
	/*#com.forbes.web.form.client.ClientLoginForm Dependency20*/
	/*
	 * Generated Methods
	 */
   
	/** 
	 * 客户登錄
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String page = request.getParameter("url");
		String content = "";
		
		URL url = new URL(Constant.UC_URL + "/" + page);//建立URL对象，并实例化为url，获得要抓取的网页地址
		//System.out.println("url = " + url);
		BufferedReader reader = new BufferedReader(new InputStreamReader(url.openStream(),"utf-8"));//建立BufferedReader对象，并实例化为reader，这里的GB2312是要抓取的网页编码格式
		String line;  
        while ((line = reader.readLine()) != null) {  
            //content += line + "\n";
            content += line;
        } 
		reader.close();
		
		request.setAttribute("RESULT_MESSAGE", content);
		
		//System.out.println("content = " + content);
		return mapping.findForward("ok");
	}
	
   

	


}