/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.video;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.service.video.VideoListManager;

/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class IndexNewAction extends Action {
	/*
	 * Generated Methods
	 */
	
	private VideoListManager videoListManager;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {		
		try {
			
			request.setAttribute( "COMMEND_VIDEO_LIST_TYPE_1", videoListManager.getTopVideoByVideoType("1", "iscommend Desc", 0, 4));
			request.setAttribute( "COMMEND_VIDEO_LIST_TYPE_5", videoListManager.getTopVideoByVideoType("5", "iscommend Desc", 0, 4));
			request.setAttribute( "COMMEND_VIDEO_LIST_TYPE_8", videoListManager.getTopVideoByVideoType("8", "iscommend Desc", 0, 4));
			request.setAttribute( "COMMEND_VIDEO_LIST_TYPE_12", videoListManager.getTopVideoByVideoType("12", "iscommend Desc", 0, 4));
			request.setAttribute( "COMMEND_VIDEO_LIST_TYPE_16", videoListManager.getTopVideoByVideoType("16", "iscommend Desc", 0, 4));
						
			request.setAttribute( "HOT_VIDEO_LIST", videoListManager.getTopVideoByVideoType(null, "click Desc", 0, 10));
			request.setAttribute( "COMP_VIDEO_LIST", videoListManager.getTopVideoByVideoType(null, "iscommend Desc", 0, 10));
			
			request.setAttribute( "VIDEO_LIST", videoListManager.getTopVideoByVideoType(null, null, 0, 9));
			request.setAttribute( "COMMEND_VIDEO_LIST", videoListManager.getTopVideoByVideoType(null, "iscommend Desc", 0, 4));
						
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public VideoListManager getVideoListManager() {
		return videoListManager;
	}
	public void setVideoListManager(VideoListManager videoListManager) {
		this.videoListManager = videoListManager;
	}
	
}