/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.feedback;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.forbes.hibernate.bean.FeedBack;
import com.forbes.service.feedback.FeedBackManager;



/** 
 * MyEclipse Struts
 * Creation date: 07-09-2007
 * 
 * XDoclet definition:
 * @struts.action path="/client/ClientLogin" name="clientLoginForm" attribute="ClientLoginForm" input="/client/ClientLogin.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/client/ClientLoginOk.jsp"
 * @struts.action-forward name="fail" path="/client/ClientLoginFail.jsp"
 */
public class SubmitFeedBackAction extends DispatchAction {
	/*#com.she.web.form.client.ClientLoginForm Dependency20*/
/*
	 * Generated Methods
	 */

	
	private  FeedBackManager feedBackManager;
	
	
	/** 
	 * 反馈
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward feed(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String email   = request.getParameter("iemail");
		String idea = request.getParameter("idea");
		
		try{
			FeedBack fd = new FeedBack();
			fd.setEmail(email);
			fd.setErrorContent(idea);
			fd.setFeedType((short)1);
			fd.setFeedTime(new Date());
			feedBackManager.addFeedBack(fd);
			request.setAttribute("OK_MESSAGE", "提交成功，我们会及时回复您，谢谢您的参与！");
			request.setAttribute("RETURN_URL", "index.jsp");
			return mapping.findForward("ok");
		}catch( Exception e ){
			e.printStackTrace();
			return mapping.findForward("fail");
		}
	}
	
	
	/** 
	 * 错误提交
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward error(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String errorUrl		= request.getParameter("url");
		String email 		= request.getParameter("email");
		String errerContent = request.getParameter("info");
		String errorType    = request.getParameter("type");
		
		try{
			FeedBack fd = new FeedBack();
			fd.setEmail(email);
			fd.setErrorUrl(errorUrl);
			fd.setErrorContent(errerContent);
			fd.setErrorType(new Short(errorType));
			fd.setFeedType((short)2);
			fd.setFeedTime(new Date());
			feedBackManager.addFeedBack(fd);
			request.setAttribute("OK_MESSAGE", "提交成功，我们会及时回复您，谢谢您的参与！");
			request.setAttribute("RETURN_URL", "index.jsp");
			return mapping.findForward("ok");
		}catch( Exception e ){
			e.printStackTrace();
			return mapping.findForward("fail");
		}
	}


	public FeedBackManager getFeedBackManager() {
		return feedBackManager;
	}


	public void setFeedBackManager(FeedBackManager feedBackManager) {
		this.feedBackManager = feedBackManager;
	}
	
	
}