/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.ask;

import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.hibernate.bean.Ask;
import com.forbes.hibernate.bean.AskAnswer;
import com.forbes.service.ask.AskAnswerManager;
import com.forbes.service.ask.AskManager;
import com.forbes.service.ask.AskSearchManager;
import com.forbes.util.Pager;



/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class IndexNewAction extends Action {
	/*
	 * Generated Methods
	 */
	//private VideoTypeManager videoTypeManager;
	
	private AskSearchManager askSearchManager;
	
	public AskSearchManager getAskSearchManager() {
		return askSearchManager;
	}

	public void setAskSearchManager(AskSearchManager askSearchManager) {
		this.askSearchManager = askSearchManager;
	}

	/*private AskManager askManager;
	
	private AskAnswerManager askAnswerManager;*/
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//System.out.println(" ask top ask list...");

		/*listAsks("0", "expiredTime desc", "not_solve_question");
		listAsks("0_1", "reward desc", "height_solve_question");
		listAsks("1", "expiredTime desc",  "already_solve_question");
		
		String status  = request.getParameter("status");
		String orderby = request.getParameter("orderby");*/
		try {
			
			//List list = askSearchManager.getTopAsk(null, status, orderby, 0, 10);

			request.setAttribute( "NOT_SOLVE_ASK_LIST", askSearchManager.getTopAsk(null, "0", "expiredTime desc", 0, 10));
			request.setAttribute( "HEIGHT_REWARDE_ASK_LIST", askSearchManager.getTopAsk(null, "0_1", "reward desc", 0, 10));
			request.setAttribute( "ALREADY_SOLVE_ASK_LIST", askSearchManager.getTopAsk(null, "1", "expiredTime desc", 0, 10));
			
			request.setAttribute( "POP_ASK_LIST", askSearchManager.getTopAsk(null, "0_1", "views desc", 0, 10));
			//System.out.println(list.size());
			
			return mapping.findForward("ok");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	
}