/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forbes.struts.action.video;

import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.forbes.service.video.VideoListManager;

/** 
 * MyEclipse Struts
 * Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class VideoTopListAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	//private VideoTypeManager videoTypeManager;
	
	private VideoListManager videoListManager;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward type(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//System.out.println(" top video list...");
		
		String  typeid = request.getParameter("typeid");
		
		try {			
			List list = videoListManager.getTopVideoByVideoType(typeid, null, 0, 7);

			request.setAttribute( "VIDEO_LIST", list);
			//System.out.println(list.size());
			
			return mapping.findForward("list");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}
	
	public VideoListManager getVideoListManager() {
		return videoListManager;
	}
	public void setVideoListManager(VideoListManager videoListManager) {
		this.videoListManager = videoListManager;
	}
	
	public ActionForward comp(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {		
		try {
			
			List hotList  = videoListManager.getTopVideoByVideoType(null, "click Desc", 0, 10);
			List compList = videoListManager.getTopVideoByVideoType(null, "iscommend Desc", 0, 10);
			
			request.setAttribute( "HOT_VIDEO_LIST", hotList);
			request.setAttribute( "COMP_VIDEO_LIST", compList);
			
			return mapping.findForward("comp");

		}catch( Exception e ){
			e.printStackTrace();
			request.setAttribute("FAIL_MESSAGE", "系统错误，请稍后再试。");
			return mapping.findForward("fail");
		}
	}

}